### ISSUE TITLE
[Bug] GUI issues

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#431]
### What is the bug?

@Leo-Peyronnet 

"Default" strings is used in two different context

Language
Theme

![image](https://user-images.githubusercontent.com/1262554/233361655-3a185a5b-5e09-442b-90f0-689717507ca1.png)

![image](https://user-images.githubusercontent.com/1262554/233361795-e92874dc-a4ac-4b78-bd4d-7d533ad66659.png)

In Italian first is female (and should be "Predefinita")
In Italian first is male (and should be "Predefinito")

I propose to create two different specific string

"Default language" (or better "System language")
"Default theme"

The relative Italian string are

"Lingua predefinita" (or better "Lingua sistema")
"Tema predefinito"

You can change to maintain consistency also

"Light" -> "Light theme" (in Italian is "Tema chiaro")
"Dark" -> "Darlk theme" (in Italian is "Tema scuro")

Please check that drop down list seems not aligned to center of line

![image](https://user-images.githubusercontent.com/1262554/233362060-2e8d3364-2bd6-43db-950e-546504cf453d.png)

Mote: About "Pinned" term (top left) is not clear the relative meaning in the context.

### How to reproduce the bug?

Use the UI

### Operating System

Windows 10

### What is the version of the operating system?

Windows 10 22H2

### What is the version of the software?

7.5.2.2304

**Comment by Leo-Peyronnet** [comment]
Thanks for your feedback, I will fix these issues.

> Please check that drop down list seems not aligned to center of line

About the alignment of the dropdowns, they are aligned to be centered vertically to their parent element:
![image](https://user-images.githubusercontent.com/55453279/233374173-a4a87a36-5066-4ac3-8acc-528607b47aa5.png)

> Note: About "Pinned" term (top left) is not clear the relative meaning in the context.

"Pinned" items are like the "main" features of the app, they are called "pinned" because they can be accessed directly. They are emphasized by the colors of the buttons.
![image](https://user-images.githubusercontent.com/55453279/233375305-69e907f6-07c0-4325-8319-6d9c942876e5.png)

**Comment by bovirus** [comment]
@Leo-Peyronnet 

If you like I can zoom the screenshot.
In my pc are not aligned to same center leve of strings.
In my pcs is not aligned but are few pixel up.

**Comment by Leo-Peyronnet** [comment]
> If you like I can zoom the screenshot. In my pc are not aligned to same center leve of strings. In my pcs is not aligned but are few pixel up.

Yes, this is intentional. They are not aligned with the strings, but to their parent element (the white rounded section). I moved them to be aligned with the expander arrow, on the right side of the parent element.
![image](https://user-images.githubusercontent.com/55453279/233381675-21cb9e5e-a75a-4685-b226-37062330d5d0.png)
