### ISSUE TITLE
[Enhancement] Add version after "Internet test" in main window

### ISSUE THREAD

**Issue by bovirus** [Leo-Corporation/InternetTest#455]
### Enhancement

Please if you can add program versiion after title.

Please screenshot

![image](https://github.com/Leo-Corporation/InternetTest/assets/1262554/620febc7-0acb-4460-b84e-c04263640970)

For any user it's easier to see the version.

**Comment by Leo-Peyronnet** [comment]
Will consider this in a future version. Thanks for the suggestion!

**Comment by bovirus** [comment]
@Leo-Peyronnet 

Save size psozion works fine. Thanks.

Why by default after installation main window height is not enough to show trace route button (see explaine din screenshot)?
Could you please increase defaullt window height to see by default "trace route buttion"?

Thanks.

**Comment by Leo-Peyronnet** [comment]
> Why by default after installation main window height is not enough to show trace route button?

This is intentional design, most relevant features are shown at the top, while other features at the bottom.

> Could you please increase default window height to see by default "trace route buttion"?

The position of the traceroute button depends on the usage of the app by the user. Now that the size of the window is saved as expected, you can just resize manually the window to see it, and it will keep it that size. 

I will add in the future an option to see all the home dashboard items by default.

You can also access the feature by using the sidebar.

**Comment by bovirus** [comment]
Thanks.
Please close the issues.
