### ISSUE TITLE
[Enhancement] Support displaying WiFi names and modifying fonts

### ISSUE THREAD

**Issue by bingsunny0730** [Leo-Corporation/InternetTest#561]
### Enhancement

1. When copying WiFi-related information, I don't know the WiFi name corresponding to this password, as shown in the picture.  It's even harder to keep track, If  connected to too many WiFi networks
![sshot-887133691](https://github.com/Leo-Corporation/InternetTest/assets/131505889/756ff295-a636-40f4-a2c8-a2b7364eab1f)
2. Add an option to modify the font pls, because the display in Simplified Chinese isn't very nice & visually appealing.

**Comment by Leo-Peyronnet** [comment]
Hi,
It seems that you have toggled "Confidential Mode" which explains why WiFi network names are not available. I think I will add the possibility to hover the WiFi name to reveal it in Confidential Mode. If you want to disable Confidential Mode, just toggle the "lock" icon in the title bar.
I will also try to implement the possibility to use different fonts instead of the default one.

Thanks for your suggestions.

**Comment by bingsunny0730** [comment]
OK, i see. I really opened Confidential Mode.😂 Thanks~~~
